"""Use real LLVM as the syntax/semantics oracle; export cases for ring3.

Requires llvmlite only on the development host. Only deterministic test
fixtures are JIT-executed here, never model replies or user input.
"""
import argparse
import ctypes
import io
import json
from pathlib import Path
import random
import subprocess

from llvmlite import binding as llvm

ROOT = Path(__file__).resolve().parents[1]
MASK = (1 << 64) - 1


def signed(value):
    value &= MASK
    return value - (1 << 64) if value >= 1 << 63 else value


def oracle(source):
    module = llvm.parse_assembly(source)
    module.verify()
    module.triple = llvm.get_default_triple()
    target = llvm.Target.from_default_triple().create_target_machine(opt=0)
    with llvm.create_mcjit_compiler(module, target) as engine:
        engine.finalize_object()
        return ctypes.CFUNCTYPE(ctypes.c_uint64)(engine.get_function_address("calc"))()


def fixtures():
    wire = io.BytesIO(subprocess.check_output([ROOT / ".build/test-ir", "--dump"]))
    while header := wire.readline():
        status, answer, length = header.split()
        source = wire.read(int(length)).decode()
        assert wire.read(1) == b"\n"
        # LLVM must accept even the valid IR which AIOS rejects at runtime
        # for division faults or poison-producing nsw overflow.
        module = llvm.parse_assembly(source)
        module.verify()
        if int(status) == 0:
            yield source, int(answer, 16)


def random_cases():
    rng = random.Random(19092026)
    edges = [-(1 << 63), (1 << 63) - 1, -207, -157, -1, 0, 1, 142, 207]
    for _ in range(96):
        lines, values = [], []
        for i in range(rng.randint(1, 20)):
            def operand():
                if values and rng.randrange(2):
                    index = rng.randrange(len(values))
                    return f"%v{index}", values[index]
                value = rng.choice(edges) if rng.randrange(2) else rng.randint(-10**9, 10**9)
                return str(value), value
            a, av = operand()
            b, bv = operand()
            op = rng.choice(["add", "sub", "mul", "sdiv"])
            if op == "sdiv" and (bv == 0 or (av == -(1 << 63) and bv == -1)):
                b, bv = "3", 3
            if op == "add":
                result = av + bv
            elif op == "sub":
                result = av - bv
            elif op == "mul":
                result = av * bv
            else:
                result = abs(av) // abs(bv) * (-1 if (av < 0) != (bv < 0) else 1)
            lines.append(f"%v{i} = {op} i64 {a}, {b}")
            values.append(signed(result))
        index = rng.randrange(len(values))
        yield "define i64 @calc() { " + " ".join(lines) + f" ret i64 %v{index} }}", values[index] & MASK
    # Exercise maximum SSA and constant-slot displacements in the real CPU.
    lines = [f"%v{i} = add i64 {i}, {i+1}" for i in range(64)]
    yield "define i64 @calc() { " + " ".join(lines) + " ret i64 %v63 }", 127
    lines = ["%v0 = add nsw i64 1, 1"] + [f"%v{i} = add nsw i64 %v{i-1}, 1" for i in range(1, 64)]
    yield "define i64 @calc() { " + " ".join(lines) + " ret i64 %v63 }", 65


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    llvm.initialize_native_target()
    llvm.initialize_native_asmprinter()
    cases = list(fixtures()) + list(random_cases())
    rows = []
    for source, expected in cases:
        actual = oracle(source)
        if actual != expected:
            raise AssertionError((source, expected, actual))
        rows.append(f"{{{json.dumps(source)}, UINT64_C({actual})}},\n")
    args.output.write_text(
        "/* Generated by real LLVM; deterministic fixtures, no model output. */\n"
        "static const struct { const char *source; uint64_t answer; } llvm_cases[]={\n"
        + "".join(rows) + "};\n")
    print(f"LLVM {'.'.join(map(str, llvm.llvm_version_info))}: verified IR and native results for {len(cases)} cases")


if __name__ == "__main__":
    main()
