#!/usr/bin/env python3
"""Generate tiny build settings; model.bin stays separate from the EFI image."""
import argparse
import hashlib
from pathlib import Path
import struct
import zlib


def write_changed(path, data):
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_suffix(path.suffix + ".tmp")
    temp.write_bytes(data)
    temp.replace(path)


def build(args):
    if not 64 <= args.context <= 8192 or not 1 <= args.tokens <= 8192:
        raise ValueError("context must be 64..8192 and tokens 1..8192")
    size = args.model.stat().st_size
    digest = hashlib.sha256()
    crc = 0
    with args.model.open("rb") as source:
        header = source.read(256)
        if (size != 964120960 or header[:8] != b"SMOLQ4\0\0" or
                struct.unpack_from("<11I", header, 8) !=
                (1, 2048, 8192, 24, 32, 32, 49152, 8192, 32, 1, 2)):
            raise ValueError("expected a SmolLM2-1.7B SMOLQ4 model")
        source.seek(0)
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
            crc = zlib.crc32(chunk, crc)
    if digest.hexdigest() != args.sha256:
        raise ValueError("model SHA-256 mismatch")
    settings = (f"/* Generated by baremetal/image.py; no model weights. */\n"
                f"#define MODEL_CRC32 0x{crc:08x}u\n"
                f"#define BOOT_CONTEXT {args.context}\n"
                f"#define BOOT_TOKENS {args.tokens}\n")
    write_changed(args.output, settings.encode())
    print(f"{args.output}: model {size:,} bytes; context {args.context}")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--model", type=Path, default=Path("model.bin"))
    p.add_argument("--sha256", required=True)
    p.add_argument("--context", type=int, default=2048)
    p.add_argument("--tokens", type=int, default=512)
    p.add_argument("--output", type=Path, default=Path(".build/config.h"))
    build(p.parse_args())
