"""Generate the pinned Unicode NFC tables (run with Python 3.13 / Unicode 15.1)."""
from pathlib import Path
import unicodedata as u

if u.unidata_version != '15.1.0':
    raise SystemExit('table generation requires Unicode 15.1.0')

decompositions, classes, compositions = [], [], []
for cp in range(0x110000):
    if 0xac00 <= cp < 0xd7a4:
        continue  # Hangul is handled algorithmically in nfc.h.
    char = chr(cp)
    ccc = u.combining(char)
    if ccc:
        classes.append((cp, ccc))
    decomposition = u.decomposition(char)
    if decomposition and not decomposition.startswith('<'):
        full = list(map(ord, u.normalize('NFD', char)))
        assert len(full) <= 4
        decompositions.append((cp, len(full), *(full + [0] * (4 - len(full)))))
        pair = [int(n, 16) for n in decomposition.split()]
        if len(pair) == 2 and u.normalize('NFC', ''.join(map(chr, pair))) == char:
            compositions.append((*pair, cp))

output = ['/* Generated by tools/generate_nfc.py; Unicode 15.1.0. */']
for name, width, rows in [('nfc_decomp', 6, decompositions),
                          ('nfc_class', 2, classes),
                          ('nfc_comp', 3, sorted(compositions))]:
    output.append(f'static const uint32_t {name}[][{width}]={{')
    output.extend('    {' + ','.join(str(n) for n in row) + '},' for row in rows)
    output.append('};')
Path('baremetal/nfc_data.h').write_text('\n'.join(output) + '\n')
