"""Split the model into FAT32-compatible files, each at most 2 GiB."""
import argparse
from pathlib import Path

PART_BYTES = 2 * 1024**3


def split_model(model, directory):
    directory.mkdir(parents=True, exist_ok=True)
    parts = []
    with model.open('rb') as source:
        remaining = model.stat().st_size
        while remaining:
            target = directory / f'model.{len(parts):03d}'
            temporary = target.with_suffix(target.suffix + '.tmp')
            count = min(remaining, PART_BYTES)
            with temporary.open('wb') as output:
                left = count
                while left:
                    chunk = source.read(min(left, 1024**2))
                    if not chunk:
                        raise ValueError('truncated model')
                    output.write(chunk)
                    left -= len(chunk)
            temporary.replace(target)
            remaining -= count
            parts.append(target)
    for stale in directory.glob('model.[0-9][0-9][0-9]'):
        if stale not in parts:
            stale.unlink()
    # This directory is generated by make; remove the obsolete single-file copy.
    (directory / 'model.bin').unlink(missing_ok=True)
    return parts


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('model', type=Path)
    parser.add_argument('directory', type=Path)
    args = parser.parse_args()
    for part in split_model(args.model, args.directory):
        print(f'{part}: {part.stat().st_size:,} bytes')
